name: Get Job Data

on:
  schedule:
    # GMT+8每週一早上8點執行
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      page:
        default: 1

jobs:
  query_data:
    runs-on: ubuntu-latest
    outputs:
      one_o_four_data: ${{ steps.query_one_o_four.outputs.data }}

    steps:
      - name: Get query string
        id: get_query_string
        shell: bash
        run: |
          query_string=""

          declare -A payload=(
            [area]="6001001004,6001001007,6001001011,6001001010"
            [jobsource]="joblist_search"
            [mode]="s"
            [order]="15"
            [scstrict]="1"
            [scmin]="60000"
            [sctp]="M"
            [sortBy]="15"
            [pageSize]="30"
            [scneg]="1"
            [page]="${{ inputs.page }}"
            [keyword]="frontend,front-end"
          )

          for key in "${!payload[@]}"; do
            value="${payload[$key]}"

            if [[ "$key" == "area" || "$key" == "keyword" ]]; then
              value="${value//,/%2C}"
            fi

            if [[ -n "$query_string" ]]; then
              query_string+="&"
            fi

            query_string+="${key}=${value}"
          done

          echo "query_string=${query_string}" >> "$GITHUB_OUTPUT"

      - name: Get random User-Agent
        id: get_ua
        run: |
          UAS=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15"
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
          )
          UA="${UAS[$RANDOM % ${#UAS[@]}]}"

          echo "user_agent=$UA" >> "$GITHUB_OUTPUT" 

      - name: query One O Four
        id: query_one_o_four
        run: |
          echo ${{ steps.get_query_string.outputs.query_string }}"
          echo ${{ steps.get_ua.outputs.user_agent }}"

      # - name: Filter Data
      #   run: |
