name: Get Job Data

on:
  schedule:
    # GMT+8每週一早上8點執行
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      page:
        default: 1
env:
  base_url: https://www.104.com.tw/jobs/search/api/jobs?
  referer_base_url: https://www.104.com.tw/jobs/search/?

jobs:
  query_data:
    runs-on: ubuntu-latest
    outputs:
      one_o_four_data: ${{ steps.query_one_o_four.outputs.data }}

    steps:
      - name: Get query string
        id: get_query_string
        shell: bash
        run: |
          query_string=""

          declare -A payload=(
            [area]="6001001004,6001001007,6001001011,6001001010"
            [jobsource]="joblist_search"
            [mode]="s"
            [order]="15"
            [scstrict]="1"
            [scmin]="60000"
            [sctp]="M"
            [sortBy]="15"
            [pageSize]="30"
            [scneg]="1"
            [page]="${{ inputs.page }}"
            [keyword]="frontend,front-end"
          )

          for key in "${!payload[@]}"; do
            value="${payload[$key]}"

            if [[ "$key" == "area" || "$key" == "keyword" ]]; then
              value="${value//,/%2C}"
            fi

            if [[ -n "$query_string" ]]; then
              query_string+="&"
            fi

            query_string+="${key}=${value}"
          done

          echo "query_string=${query_string}" >> "$GITHUB_OUTPUT"

      - name: Get random User-Agent
        id: get_user_agent
        run: |
          UAS=(
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:142.0) Gecko/20100101 Firefox/142.0"
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Safari/605.1.15"
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
          )
          UA="${UAS[$RANDOM % ${#UAS[@]}]}"

          echo "user_agent=$UA" >> "$GITHUB_OUTPUT" 

      - name: Get Referer
        id: get_referer
        run: |
          # 等同於 Python: url.encode("unicode_escape").decode("utf-8")
          # 這是要把中文轉unicode，避免keyword有中文時，會報latin-1的錯誤
          referer=$(printf '%s' "${{ env.referer_base_url }}${{ steps.get_query_string.outputs.query_string }}" | jq -Rsa . | sed 's/^"//; s/"$//')

          echo $referer
          echo "referer=$referer" >> "$GITHUB_OUTPUT"

      - name: query One O Four
        id: query_one_o_four
        run: |
          echo "Sending GET request to: ${{ env.base_url }}"

          response=$(curl --fail --silent --show-error \
            -H 'Accept: application/json, text/plain, */*' \
            -H 'Accept-Encoding: gzip, deflate, br, zstd' \
            -H 'Accept-Language: zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6' \
            -H 'Connection: keep-alive' \
            -H 'Cookie: luauid=2002202007; ACUD=870d783a-454b-491a-a8de-6f66f272665c; _ga=GA1.4.1113649282.1752891799; _hjSessionUser_3218023=eyJpZCI6IjU0ZjI1NmNiLWIzNWQtNTYyYi04MTkyLWM0NTBjYTg0YWI5YyIsImNyZWF0ZWQiOjE3NTcxMzg2NzA3MzYsImV4aXN0aW5nIjp0cnVlfQ==; _hjMinimizedPolls=1539041; FOLLOW_JOB_PROMPT=0; _hjSessionUser_642678=eyJpZCI6IjlkMDU5OTFkLTkyMzAtNTg5ZS1iZDc4LTQ2ZGE3NjgwMmFmMyIsImNyZWF0ZWQiOjE3NTcxNDAyNzUyNzQsImV4aXN0aW5nIjp0cnVlfQ==; FOLLOW_COMPANY_PROMPT=0; _hp2_id.3192618648=%7B%22userId%22%3A%228929110875571733%22%2C%22pageviewId%22%3A%227561259521281730%22%2C%22sessionId%22%3A%225294798232380197%22%2C%22identity%22%3Anull%2C%22trackerVersion%22%3A%224.0%22%7D; _ga_TTXLT7SQ8E=GS2.1.s1764596043$o3$g1$t1764596051$j52$l0$h0; _hjDonePolls=787456; _clck=1si1jxu%5E2%5Eg1p%5E0%5E2041; c_job_search=1; EPK=7aa8618f-fe08-4a6f-982e-640f9f8fdae8; LLM=identity; _fbp=fb.2.1781663506357.8731815597616240; _ga_W9X1GB1SVR=GS2.1.s1783405722$o31$g1$t1783410501$j60$l0$h0; _ga_FJWMQR9J2K=GS2.1.s1783405722$o31$g1$t1783410501$j60$l0$h0; _ga_WYQPBGBV8Z=GS2.4.s1783405722$o30$g1$t1783410501$j60$l0$h0; _T_MYPOOL_104I=2; personal-recommend-jobs-groups=2; PROTOCOL104=http; job_same_ab=2; bprofile_actor_id=29e48e2ee0df790e859236e5bca56553; bprofile_history=%5B%22130000000218130%22%5D; cust_same_ab=2; c_job_view_job_info_nabi=7hxk9%2C2013001006; _cfuvid=J.DjYNOLn1mlqxjFJPxXG56qchqbuzb7ddNW9cX_f0Q-1790651195.0782979-1.0.1.1-WlZY2uaD9Z.PRRQSGG.SNccVvZJty0icsIa3wuv427o; AC=1790651195; _f=eyJpdiI6ImVvZitVQnJLY0x1c0tSMFA4QzJMQXc9PSIsInZhbHVlIjoiVWlkTlRjVm5LYm5wazZMTDdZd0pHR2YvZkJRSWplYk03Y3VqbzRJdXExM2V0dm5mQ2pMUnV1cDk2YUxaL2VqM2pwek9RRzU0b0dmVHBkTFZuejlLRGc9PSIsIm1hYyI6IjRkZTFhOWZkNGFjNWYyM2U3M2M4OGQ2OGYyNzllYzcyZjdkMDEzNDgzMWZlZTRkMDRlZGIyZDNiYjY5NWQyMjkiLCJ0YWciOiIifQ%3D%3D; JBCLOGIN=M6FKq6GsIkjL9ciIqf25C6XR70eCj8pOTbHvS00Nglh8V; c_login_return_7aa8618f-fe08-4a6f-982e-640f9f8fdae8_pc=1; c_white_bar_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2pvYi1ub3RpZnkuMTA0ZGMuY29tIiwic3ViIjoiJCQ6djE6MnRUUDZEVXhiMHBhTnY4WXhUQWZiSFg0eXRKQmllSFNoNW9mSGNUOTdReHpYSUJGWnRyMHpqOCIsImlhdCI6MTc5MDY2NDk0OS44NjUzNzUsImV4cCI6MTc5MDY2ODU0OS44NjUzNzV9.2yz2xMKGm0rwu7kSpgQ-57rVTY4q4pS9Hwa9kQa8btM%2CeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJub3RpZmljYXRpb24uMTA0ZGMuY29tIiwiaWF0IjoxNzkwNjY0OTUwLjE4LCJleHAiOjE3OTA2Njg1NTAuMTgsInByb2R1Y3QiOiJqb2Jfbm90aWZ5X3NlcnZpY2UiLCJlbmRwb2ludCI6ImNfZmYxZDU3YWY4MmRjNDJmMjA4MDUwOWRkNjE2NjlhMTgifQ.om-v_DSZYCksKrOIPv2UHpvcJ9ddXkJuba0pbVmvDDw; c_white_bar_token_authentication=b7c52e2daf25b75591a1b5665d9fc779; c_white_bar_latest_match_time=2026-09-29%2014%3A55%3A42; lup=2002202007.5003636897510.4623532291991.1.4640712161167; lunp=4623532291991; cf_clearance=rb4GjFs2tml.1CoGODvEo3yJLAZ4PMmFnP6E.73M0_k-1790666337-1.2.1.1-E4D69EpKkXR.HEN4dHYldKq1yuJL3YSZkm_Na67_2cXiCMF9PXKmZYlQiX.Jja29B1_FmQ2F1Qqwqrd4dS2mTrIHAHwOHMJf7CSfL4wumZPjeye2TQk6rsrMpvk_Bd7I5R4GUNmZjl8lYKgJiBRZXwwYwe_mRC.y5f4GRNE.btfwNiWABPAxPc01A6QVRiKydWp4GqUU6rImQPMZxOSuoJNSQSldSIskDS2IyHXCbC4oA820Lvjlz9FSMcOsxUWGGe.vbbrQdAjuPjBaEe9Hl97k0.ACXikFoI7vHPcso.h5TCaStoVYsWn8zqAwclm07yDkb9MHDS7uxSmy_HV_QPEc6Z6F3MboCtPfEqrAb6myI3TFFTgLcHkgU6VeonKoyXIo8JzkbY7RyypZt8SSMQ; __cf_bm=zRnlqJy3Uu5k0TIl4MUd1_2BpJlB4ycdDpnkIa5E5NE-1790666337.076051-1.0.1.1-wStYkSwABylBBew1LLIII.PBd6vA0Keh1Vky.AlIkqJzYfqqz_RFTP9wroOkz_uwNwwQBaQI_pyQr.KnOPbyHfWv7SRKZjMqyQMAamo2T4zM9.93VFY.PHgsFSGTKqGK' \
            -H 'Host: www.104.com.tw' \
            -H 'Referer: https://www.104.com.tw/jobs/search/?scstrict=1&sortBy=15&scmin=60000&scneg=1&area=6001001004,6001001007,6001001011,6001001010&mode=s&jobsource=joblist_search&keyword=frontend&sctp=M&page=1&pageSize=30&order=15' \
            -H 'Sec-Fetch-Dest: empty' \
            -H 'Sec-Fetch-Mode: cors' \
            -H 'Sec-Fetch-Site: same-origin' \
            -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36' \
            -H 'sec-ch-ua: "Chromium";v="154", "Google Chrome";v="154", "Not A(Brand";v="99"' \
            -H 'sec-ch-ua-arch: "x86"' \
            -H 'sec-ch-ua-bitness: "64"' \
            -H 'sec-ch-ua-full-version: "154.0.8037.58"' \
            -H 'sec-ch-ua-mobile: ?0' \
            -H 'sec-ch-ua-platform: "Windows"' \
            -H 'sec-ch-ua-platform-version: "19.0.0"' \
            "https://www.104.com.tw/jobs/search/api/jobs?area=6001001004%2C6001001007%2C6001001011%2C6001001010&jobsource=joblist_search&keyword=frontend&mode=s&order=15&page=1&pageSize=30&pagesize=20&personalBoost=1&scmin=60000&scneg=1&scstrict=1&sctp=M&sortBy=15")

          echo ${{ steps.get_referer.outputs.referer }}
          echo "${{ env.base_url }}${{ steps.get_query_string.outputs.query_string }}"

          echo "Response:"
          echo "$response"

          {
            echo 'response<<EOF'
            echo "$response"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

      # - name: Filter Data
      #   run: |
